export const FIND_ALL_COURSES = 'FIND_ALL_COURSES';
export const FIND_MODULES_FOR_COURSE = 'FIND_MODULES_FOR_COURSE';
export const FIND_LESSONS_FOR_MODULE = 'FIND_LESSONS_FOR_MODULE';
export const FIND_TOPICS_FOR_LESSON = 'FIND_TOPICS_FOR_LESSON';
export const FIND_WIDGETS_FOR_LESSON_TOPIC = 'FIND_WIDGETS_FOR_LESSON_TOPIC';